### PR TITLE
New design applied to the sample, updated styles and layout

### PR DESCRIPTION
**Pull request by didiepetrova**

### CODE REVIEW

**Comment by TsvetinaIvanova** [comment]
Seems like the screenshot has been deleted. If this is on purpose, remove it from the ReadMe. 

Also, remove the <title> tag from index.html.

One additional thing that isn't a must - you can check if all listed Android permissions are indeed requried by the plugin.

**Comment by TsvetinaIvanova** [comment]
Rebase from master to resolve conflicts.

**Comment by TsvetinaIvanova** [comment]
:+1:

**Comment by AntonDobrev** [comment]
We do not need the permissions for Android, it would be wise to remove them from Android Permissions set - in regard to location, receive sms, etc. Otherwise - :+1:

**Comment by AntonDobrev** [comment]
We also need the viewport setting in index.html

**Comment by didiepetrova** [comment]
Comments applied.

**Pull request merged**
